### ISSUE TITLE
Nail down App dependencies

### ISSUE THREAD

**Issue by gaf3** [klot-io/pi-setup#8]
Ya, it's time. So all we need is to say :

```
  requires:
  - site: github.com
    repo: nandy-io/chore
  - site: github.com
    repo: nandy-io/speech
```

And if the child service know that much about the parent service, it knows what to set it's settings to.
